<?php

// autoload.php generated by Composer

require_once __DIR__ . '/vendor/autoload.php';

// Your success page code here

return ComposerAutoloaderInit16e743149d3340303a4c6a282649422d::getLoader();
?>
